In [ ]:
#1
import numpy as np

a = np.arange(1, 10)
table = a.reshape(9, 1) * a
print(table)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [ ]:
#2
def arithmetic_matrix(n, first, diff):
    arr = np.arange(first, first + n * diff, diff)
    matrix = np.diag(arr)
    return matrix

print(arithmetic_matrix(5, 1.5, -0.5))

[[ 1.5  0.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0. ]
 [ 0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5]]


In [ ]:
#3
A = np.arange(1, 26).reshape(5, 5)

odd_elements = A[::2, ::2].flatten()

print(odd_elements)

[ 1  3  5 11 13 15 21 23 25]


In [ ]:
#4
arr = np.zeros((5,5))
arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#5
arr1 = np.zeros((5,5))
arr1[::2,::2] = 5
arr1[1::2,1::2] = 5
print(arr1)

arr2 = np.zeros((5,5))
for i in range(5):
    for j in range(i+1):
        arr2[i,j] = 5
print(arr2)

det1 = np.linalg.det(arr1)
inv1 = np.linalg.inv(arr1)

det2 = np.linalg.det(arr2)
inv2 = np.linalg.inv(arr2)

print(det1)
print(inv1)

print(det2)
print(inv2)

[[5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]]
[[5. 0. 0. 0. 0.]
 [5. 5. 0. 0. 0.]
 [5. 5. 5. 0. 0.]
 [5. 5. 5. 5. 0.]
 [5. 5. 5. 5. 5.]]


LinAlgError: ignored

In [ ]:
#6-9
import pandas as pd
df = pd.read_csv('/content/estate.txt')

print(df.head())

print(df.tail())

print(df.info())

      Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2       